name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "case3-umkm/frontend/**" # only trigger when something in Frontend changes

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: case3-umkm/frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
        env:
          VITE_SERVICE_ID: ${{ secrets.VITE_SERVICE_ID }}
          VITE_TEMPLATE_ID: ${{ secrets.VITE_TEMPLATE_ID }}
          VITE_PUBLIC_ID: ${{ secrets.VITE_PUBLIC_ID }}
          VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: case3-umkm/frontend/dist

  deploy:
    name: Deploy Frontend
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist # download to root ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
